### ISSUE TITLE
Exception thrown by .net Framework.

### ISSUE THREAD

**Issue by Ashthos** [TalAloni/SMBLibrary#249]
Hi, 

Getting this exception thrown. Appears to be an issue with the .net framework or SMBLibrary's communication with it.

SMBLibrary v1.5.0.1
.net8.0 running on Windows 10.

```
Unhandled exception. System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.
   at System.DateTime.ToFileTimeLeapSecondsAware(Int64 ticks)
   at System.DateTime.ToFileTimeUtc()
   at SMBLibrary.SetFileTime.ToFileTimeUtc()
   at SMBLibrary.FileTimeHelper.WriteSetFileTime(Byte[] buffer, Int32 offset, SetFileTime time)
   at SMBLibrary.FileBasicInformation.WriteBytes(Byte[] buffer, Int32 offset)
   at SMBLibrary.Server.SMB2.QueryInfoHelper.GetQueryInfoResponse(QueryInfoRequest request, ISMBShare share, SMB2ConnectionState state)
   at SMBLibrary.Server.SMBServer.ProcessSMB2Command(SMB2Command command, SMB2ConnectionState state)
   at SMBLibrary.Server.SMBServer.ProcessSMB2RequestChain(List`1 requestChain, ConnectionState& state)
   at SMBLibrary.Server.SMBServer.ProcessPacket(SessionPacket packet, ConnectionState& state)
   at SMBLibrary.Server.SMBServer.ProcessConnectionBuffer(ConnectionState& state)
   at SMBLibrary.Server.SMBServer.ReceiveCallback(IAsyncResult result)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by TalAloni** [comment]
What is the value being represented here?
There was a similar issue with a file date set in the year 30280 ( https://github.com/TalAloni/SMBLibrary/pull/183 )
Not all FileTime values can be represented by the framework, anything later than the year 9999 is problematic.

**Comment by frogcrush** [comment]
I'm encounting this issue as well. I've tried DateTime.FromFileTime(0), new DateTime(), DateTime.Now, and a parsed DateTime for the current date. 

I'm using .NET 8 and the program is running in a Linux Docker container.

**Comment by TalAloni** [comment]
Hi Tylor, same question - what is the value being represented?

**Comment by TalAloni** [comment]
Calling .ToFileTimeUtc() on .NET 8.0 seems to work for me without issues for DateTime.Now, so I have to suspect that the issue is with the DateTime value.

**Comment by TalAloni** [comment]
According to [the docs ](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tofiletimeutc?view=net-8.0)this exception will be thrown if "The resulting file time would represent a date and time before 12:00 midnight January 1, 1601 C.E. UTC."

**Comment by TalAloni** [comment]
You can make an argument for treating any value < year 1601 as DateTime.MinValue, if that's indeed the issue.
This can also be done at the INTFileStore implementation level without modifications to the library.

**Comment by Ashthos** [comment]
I suspect my issue was due to a DateTime.MinValue being set. I've not been able to reliably replicate the exception however.
