### ISSUE TITLE
NullReferenceException crashing the application simmilar to #257

### ISSUE THREAD

**Issue by xitac** [TalAloni/SMBLibrary#271]
Hi,
we're using version 1.5.3.5, and from time to time, we get the exception with the stack trace from below. I noticed that every time, just before this happens, we get STATUS_IO_TIMEOUT connection status. Then, on retrying the connection, the app crashes. 
Setting higher responseTimeoutInMilliseconds to SMB2Client.Connect helps, but doesn't seem like a good permanent solution. 

Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Utilities.ByteReader.ReadByte(Byte[] buffer, Int32 offset)
   at SMBLibrary.NetBios.SessionPacket.GetSessionPacketLength(Byte[] buffer, Int32 offset)
   at SMBLibrary.NetBios.NBTConnectionReceiveBuffer.HasCompletePacket()
   at SMBLibrary.Client.SMB2Client.ProcessConnectionBuffer(ConnectionState state)
   at SMBLibrary.Client.SMB2Client.OnClientSocketReceive(IAsyncResult ar)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by TalAloni** [comment]
if you get STATUS_IO_TIMEOUT you shouldn't retry the connection, you should start a new connection.
the existing connection is not salvable, one cannot easily determine if the data being received is the old reply or reply to the new command.

**Comment by TalAloni** [comment]
Please review your code and ensure that you are not attempting to reuse the existing connection, if I misunderstood the issue, please update.

**Comment by xitac** [comment]
Yes, sorry, I wasn't entirely clear about the retry. When retrying, we're not reusing existing connections. We're instantiating a new instance of SMB2Client and getting the new fileStore by client.TreeConnect.  

We're getting the STATUS_IO_TIMEOUT from the fileStore.ReadFile after which we throw an exception. The exception is handled and everything is retried. 

One other thing to note that might be interesting is that we have up to 2 threads connecting to shared folder (each instantiating its own smb client instance), and they both get the STATUS_IO_TIMEOUT at almost the same time (few millisecond difference). So I guess something happens with the shared folder or the network connection.

We've been happily using the library in the same manner for at least a year and this only seems to happen with one specific shared folder we're connecting to. It's on the client's environment so we're restricted in what we can do. On our environment we couldn't reproduce the issue. 

I'll take another deeper look into the code, but currently I don't see any possibility of reusing existing connection in it.

**Comment by TalAloni** [comment]
Thanks for the clarification,
I'm assuming each thread is only dealing with its own SMB2Client.
Do you use the ReleaseConnection API?
Do you use the Disconnect API in a non-trivial manner?
One scenario that I can think of is that one of these APIs is invoked by your code immediately after OnClientSocketReceive is invoked.

**Comment by TalAloni** [comment]
on any exception (that indicates the connection is unhealthy) the client will close the socket and dispose of the buffer so there is no need to disconnect.
However for STATUS_IO_TIMEOUT, since technically the connection is known to be healthy, In v1.5.3.5 the client keeps the socket open and does not dispose of the buffer.
However, in both cases calling Disconnect following the exception / STATUS_IO_TIMEOUT should be fine (for the former it does nothing and for the latter we use a lock on the buffer to ensure cleanup in an orderly fashion), so finally looks fine.

If OnClientSocketReceive obtained the lock first, then the Disconnect will wait for the buffer lock to be freed, so the buffer shouldn't be read from.
And if OnClientSocketReceive is invoked and then at the same time, before we obtain the lock on the buffer there, we Disconnect and free the buffer, then IIUC EndReceive should throw ObjectDisposedException (.NET 6.0) / SocketException (.NET 7.0+), and again the buffer shouldn't be read from.

It's not clear to me what is the scenario that will cause EndReceive to succeed after we already closed and disposed of the socket. I was not able to recreate this scenario.

Which .NET version are you using BTW?

**Comment by xitac** [comment]
Oh, right, the lock is on the buffer so this shouldn't happen.
We're using .net 8.0.

**Comment by TalAloni** [comment]
I was not able to recreate this scenario. it would be helpful if you could help reproduce the issue.

**Comment by xitac** [comment]
I couldn't reproduce the issue in my environment either; it only seems to occur in this one client's setup. I'll reach out to them to arrange some testing on their end.

**Comment by TalAloni** [comment]
Closing due to no activity / additional information.
