### ISSUE TITLE
An error occurs when trying to run the driver installation file.

### ISSUE THREAD

**Issue by nvd05** [TalAloni/SMBLibrary#281]
+ When trying to open the installation `.exe` file via SMB, an error occurs.
+ PowerShell: `dotnet run --project SMBServer`
+ Usage `v1.5.3`

```
Unhandled exception. SMBLibrary.UnsupportedInformationLevelException: Unsupported information class: 59
   at SMBLibrary.FileInformation.GetFileInformation(Byte[] buffer, Int32 offset, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary\NTFileStore\Structures\FileInformation\FileInformation.cs:line 91
   at SMBLibrary.Win32.NTDirectoryFileSystem.GetFileInformation(FileInformation& result, Object handle, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary.Win32\NTFileStore\NTDirectoryFileSystem.cs:line 298
   at SMBLibrary.Server.SMB2.QueryInfoHelper.GetQueryInfoResponse(QueryInfoRequest request, ISMBShare share, SMB2ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMB2\QueryInfoHelper.cs:line 39
   at SMBLibrary.Server.SMBServer.ProcessSMB2Command(SMB2Command command, SMB2ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 174
   at SMBLibrary.Server.SMBServer.ProcessSMB2Command(SMB2Command command, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 114
   at SMBLibrary.Server.SMBServer.ProcessSMB2RequestChain(List`1 requestChain, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 52
   at SMBLibrary.Server.SMBServer.ProcessPacket(SessionPacket packet, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 406
   at SMBLibrary.Server.SMBServer.ProcessConnectionBuffer(ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 317
   at SMBLibrary.Server.SMBServer.ReceiveCallback(IAsyncResult result) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 277
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. SMBLibrary.UnsupportedInformationLevelException: Unsupported information class: 59
   at SMBLibrary.FileInformation.GetFileInformation(Byte[] buffer, Int32 offset, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary\NTFileStore\Structures\FileInformation\FileInformation.cs:line 91
   at SMBLibrary.Win32.NTDirectoryFileSystem.GetFileInformation(FileInformation& result, Object handle, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary.Win32\NTFileStore\NTDirectoryFileSystem.cs:line 298
   at SMBLibrary.Server.SMB2.QueryInfoHelper.GetQueryInfoResponse(QueryInfoRequest request, ISMBShare share, SMB2ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMB2\QueryInfoHelper.cs:line 39
   at SMBLibrary.Server.SMBServer.ProcessSMB2Command(SMB2Command command, SMB2ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 174
   at SMBLibrary.Server.SMBServer.ProcessSMB2Command(SMB2Command command, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 114
   at SMBLibrary.Server.SMBServer.ProcessSMB2RequestChain(List`1 requestChain, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB2.cs:line 39
   at SMBLibrary.Server.SMBServer.ProcessPacket(SessionPacket packet, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 406
   at SMBLibrary.Server.SMBServer.ProcessConnectionBuffer(ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 317
   at SMBLibrary.Server.SMBServer.ReceiveCallback(IAsyncResult result) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 277
   at System.Threading.Tasks.TaskToAsyncResult.TaskAsyncResult..ctor(Task task, Object state, AsyncCallback callback)
   at System.Threading.Tasks.TaskToAsyncResult.Begin(Task task, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at SMBLibrary.Server.SMBServer.ReceiveCallback(IAsyncResult result) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 283
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I noticed that when trying to view a specific folder, an error occurs:

```
Unhandled exception. SMBLibrary.UnsupportedInformationLevelException: Unsupported information class: 71
   at SMBLibrary.FileInformation.GetFileInformation(Byte[] buffer, Int32 offset, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary\NTFileStore\Structures\FileInformation\FileInformation.cs:line 91
   at SMBLibrary.Win32.NTDirectoryFileSystem.GetFileInformation(FileInformation& result, Object handle, FileInformationClass informationClass) in D:\services\SMBLibrary\SMBLibrary.Win32\NTFileStore\NTDirectoryFileSystem.cs:line 298
   at SMBLibrary.Server.SMB1.SMB1FileStoreHelper.GetFileInformation(FileInformation& result, INTFileStore fileStore, String path, FileInformationClass informationClass, SecurityContext securityContext) in D:\services\SMBLibrary\SMBLibrary\Server\SMB1\SMB1FileStoreHelper.Query.cs:line 42
   at SMBLibrary.Server.SMB1.Transaction2SubcommandHelper.GetSubcommandResponse(SMB1Header header, UInt32 maxDataCount, Transaction2QueryPathInformationRequest subcommand, ISMBShare share, SMB1ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMB1\Transaction2SubcommandHelper.cs:line 256
   at SMBLibrary.Server.SMB1.TransactionHelper.GetCompleteTransaction2Response(SMB1Header header, UInt32 maxDataCount, Byte[] requestSetup, Byte[] requestParameters, Byte[] requestData, ISMBShare share, SMB1ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMB1\TransactionHelper.cs:line 217
   at SMBLibrary.Server.SMB1.TransactionHelper.GetTransactionResponse(SMB1Header header, TransactionRequest request, ISMBShare share, SMB1ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMB1\TransactionHelper.cs:line 55
   at SMBLibrary.Server.SMBServer.ProcessSMB1Command(SMB1Header header, SMB1Command command, SMB1ConnectionState state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB1.cs:line 249
   at SMBLibrary.Server.SMBServer.ProcessSMB1Command(SMB1Header header, SMB1Command command, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB1.cs:line 115
   at SMBLibrary.Server.SMBServer.ProcessSMB1Message(SMB1Message message, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.SMB1.cs:line 27
   at SMBLibrary.Server.SMBServer.ProcessPacket(SessionPacket packet, ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 373
   at SMBLibrary.Server.SMBServer.ProcessConnectionBuffer(ConnectionState& state) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 317
   at SMBLibrary.Server.SMBServer.ReceiveCallback(IAsyncResult result) in D:\services\SMBLibrary\SMBLibrary\Server\SMBServer.cs:line 277
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by TalAloni** [comment]
There is no installer and there is no driver as part of the SMBLibrary project.
There is a sample application and I understand that you experience it crashing when an SMB client is performing some operation. please provide details about the client.

**Comment by nvd05** [comment]
+ Client: Standard Windows 10 Explorer.

**Comment by nvd05** [comment]
I'll add more information later:

+ the package itself in debug mode.
+ a snapshot of the list of files in the folder.

I think she should help you.
